# Generated by Django 5.1 on 2024-08-20 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Agents",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom_Agents", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Clients",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom_clients", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="MiseAJour",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("version_Logiciel", models.CharField(max_length=50)),
                (
                    "type_logiciel",
                    models.CharField(
                        choices=[("Brel-Eco", "Brel-Eco"), ("Brel-Gest", "Brel-Gest")],
                        max_length=10,
                    ),
                ),
                ("poste_concerne", models.CharField(max_length=100)),
                ("addresse_MAC", models.CharField(max_length=17)),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="update_logiciel.agents",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="update_logiciel.clients",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HistoriqueMiseAJour",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mise_a_jour",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="update_logiciel.miseajour",
                    ),
                ),
            ],
        ),
    ]
