# Generated by Django 5.1 on 2024-08-21 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("update_logiciel", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="miseajour",
            name="agent",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="miseajour",
            name="client",
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name="Agents",
        ),
        migrations.DeleteModel(
            name="Clients",
        ),
    ]
