# Generated by Django 5.1 on 2024-08-21 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "update_logiciel",
            "0002_alter_miseajour_agent_alter_miseajour_client_and_more",
        ),
    ]

    operations = [
        migrations.DeleteModel(
            name="HistoriqueMiseAJour",
        ),
    ]
